// OAuth cases adapted from Carried core/auth/tests/oauth.test.ts (Apache-2.0).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtemp, rm, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createAuthorizationRequest, exchangeAuthorizationCode, loginWithBrowser } from '../src/auth/codex-oauth.ts';
import { FileCredentialStore, MemoryCredentialStore } from '../src/auth/credential-store.ts';
import { OAuthAccount } from '../src/auth/account.ts';
import { Subscription } from '../src/auth/subscription.ts';
import { setTimeout } from 'node:timers/promises';
import { credential } from './fixtures/model.ts';

test('PKCE and state are generated by the host and cannot be overridden by URL parameters', () => {
  const auth = createAuthorizationRequest({ authorize_params: { state: 'attacker', code_challenge: 'attacker' } }, 'http://localhost:1455/auth/callback');
  const url = new URL(auth.url);
  assert.equal(url.searchParams.get('state'), auth.state);
  assert.equal(url.searchParams.get('code_challenge'), createHash('sha256').update(auth.pkce.verifier).digest('base64url'));
  assert.notEqual(auth.state, 'attacker');
  assert.throws(() => createAuthorizationRequest({}, 'https://untrusted.example/callback'));
});

test('subscription login is one host-owned flow and status never exposes credentials', async () => {
  const store = new MemoryCredentialStore(); let changed = 0;
  const subscription = new Subscription(store, () => { changed++; }, { callback_host: '127.0.0.1', callback_port: 0,
    fetch: async () => Response.json({ access_token: 'artificial-access', refresh_token: 'artificial-refresh', expires_in: 3600 }) });
  try {
    const first = subscription.start(); assert.equal(subscription.start(), first);
    const url = new URL(await first); const callback = new URL(url.searchParams.get('redirect_uri')!);
    callback.searchParams.set('state', url.searchParams.get('state')!); callback.searchParams.set('code', 'artificial-code');
    await fetch(callback);
    for (let n = 0; n < 100 && (await subscription.status()).pending; n++) await setTimeout(10);
    const status = await subscription.status(); assert.equal(status.connected, true); assert.equal(status.url, null);
    assert.doesNotMatch(JSON.stringify(status), /artificial-access|artificial-refresh/);
    await subscription.logout(); assert.equal((await subscription.status()).connected, false);
    assert.ok(changed >= 2);
    await subscription.start(); await subscription.close(); assert.equal((await subscription.status()).pending, false);
    assert.equal(await store.read(), undefined);
  } finally { await subscription.close(); }
});

test('OAuth requires opt-in and validates callback state without contacting the real token server', async () => {
  await assert.rejects(loginWithBrowser({}), { code: 'EXPERIMENTAL_OPT_IN_REQUIRED' });
  let exchanges = 0;
  await assert.rejects(loginWithBrowser({ experimental_opt_in: true, callback_host: '127.0.0.1', callback_port: 0,
    open_external: async url => {
      const auth = new URL(url);
      const callback = new URL(auth.searchParams.get('redirect_uri')!);
      callback.searchParams.set('state', 'invalid-state'); callback.searchParams.set('code', 'artificial-code');
      await fetch(callback);
    },
    fetch: async () => { exchanges++; return Response.json({}); },
  }), { code: 'STATE_MISMATCH' });
  assert.equal(exchanges, 0);
});

test('token exchange is bounded, validates credentials and disallows redirects', async () => {
  const input = { code: 'artificial-code', redirect_uri: 'http://localhost:1455/auth/callback', verifier: 'artificial-verifier' };
  const saved = await exchangeAuthorizationCode({ fetch: async (_url, init) => {
    assert.equal(init?.redirect, 'error');
    return Response.json({ access_token: 'artificial-access', refresh_token: 'artificial-refresh', expires_in: 3600 });
  } }, input);
  assert.equal(saved.refresh_token, 'artificial-refresh');
  await assert.rejects(exchangeAuthorizationCode({ fetch: async () => Response.json({ access_token: 'bad\nheader', refresh_token: 'refresh' }) }, input),
    { code: 'TOKEN_RESPONSE_INVALID' });
  await assert.rejects(exchangeAuthorizationCode({ token_exchange_timeout_ms: 20, fetch: async () => new Promise(() => undefined) }, input),
    { code: 'TOKEN_EXCHANGE_TIMEOUT' });
});

test('explicit credential file survives restart, rejects malformed data and clears without fallback', async t => {
  const root = await mkdtemp(join(tmpdir(), 'niwa-auth-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  const path = join(root, 'secrets', 'codex.json');
  const store = new FileCredentialStore(path);
  assert.equal(await store.read(), undefined);
  await store.write(credential);
  assert.deepEqual(await new FileCredentialStore(path).read(), credential);
  assert.equal(JSON.parse(await readFile(path, 'utf8')).access_token, credential.access_token);
  assert.throws(() => new FileCredentialStore('relative.json'));
  assert.throws(() => store.write({ ...credential, refresh_token: '\n' }));
  await store.clear();
  assert.equal(await new FileCredentialStore(path).read(), undefined);
});

test('account refresh is shared, and logout prevents late refresh from resurrecting credentials', async () => {
  const store = new MemoryCredentialStore();
  let exchanges = 0;
  let finish!: (value: typeof credential) => void;
  const account = new OAuthAccount(store, async () => { exchanges++; return new Promise(resolve => { finish = resolve; }); });
  await account.login(credential);
  const first = account.refresh(credential.refresh_token);
  const second = account.refresh(credential.refresh_token);
  await new Promise(resolve => setImmediate(resolve));
  assert.equal(exchanges, 1);
  finish({ ...credential, refresh_token: 'artificial-rotated' });
  assert.deepEqual(await first, await second);
  await account.refresh(credential.refresh_token);
  assert.equal(exchanges, 1);
  const stale = account.refresh('artificial-rotated');
  await new Promise(resolve => setImmediate(resolve));
  await account.clear();
  finish({ ...credential, refresh_token: 'artificial-stale' });
  await assert.rejects(stale, /Login changed/);
  assert.equal(await account.read(), undefined);
});
