import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {Runtime} from '../src/runtime/runtime.ts';
function fixture(t:{after(fn:()=>void):void}){const root=mkdtempSync('/tmp/niwa-business-'),r=new Runtime(root),admin=r.administrator(),a=r.bootstrap(admin),aa=r.agentSession(a.id),b=r.createAgent(aa,'担当Bot'),ba=r.agentSession(b.id),room=r.createRoom(admin,'人工案件');t.after(()=>{r.close();rmSync(root,{recursive:true,force:true});});return {r,admin,a,aa,b,ba,room};}
test('delegated registration attaches to original purpose; continuation and retry retain task and label',t=>{
 const {r,admin,a,aa,b,ba,room}=fixture(t);const parent=r.tasks.create(admin,a.id,room.id,'売上を検証する'),lease=r.tasks.claim(admin)!;r.registerBusinessTask(aa,lease,'需要の検証','根拠を調べる');const child=r.tasks.delegate(aa,lease,b.id,'公開資料を集める'),cl=r.tasks.claim(admin)!;
 r.registerBusinessTask(ba,cl,'資料調査','担当部分');r.registerBusinessTask(ba,cl,'資料調査の続き','担当部分の続き');assert.equal(r.businessTasks(admin).length,1);assert.equal(r.businessTasks(admin)[0]!.title,'需要の検証');assert.equal(r.tasks.workRoot(admin,child.id),parent.id);
 r.reportAndContinue(ba,cl,'途中報告','照合する',0,'report');const next=r.tasks.claim(admin)!;assert.equal(next.task.id,child.id);r.registerBusinessTask(ba,next,'照合','続行');r.tasks.cancel(admin,child.id);r.tasks.cancel(admin,parent.id);r.tasks.retry(admin,parent.id);assert.equal(r.tasks.workRoot(admin,child.id),parent.id);assert.equal(r.businessTasks(admin).length,1);assert.equal(r.tasks.list(admin).length,2);
});
test('child-first registration uses parent purpose, while unrelated equal titles stay separate',t=>{
 const {r,admin,a,aa,b,ba,room}=fixture(t);const root=r.tasks.create(admin,a.id,room.id,'親の目的'),lease=r.tasks.claim(admin)!,child=r.tasks.delegate(aa,lease,b.id,'部分作業'),cl=r.tasks.claim(admin)!;r.registerBusinessTask(ba,cl,'短い作業','部分作業');assert.equal(r.businessTasks(admin)[0]!.task_id,root.id);assert.equal(r.businessTasks(admin)[0]!.title,'親の目的');
 const other=r.tasks.create(admin,a.id,room.id,'親の目的'),ol=r.tasks.claim(admin)!;r.registerBusinessTask(aa,ol,'親の目的','別依頼');assert.equal(r.businessTasks(admin).length,2);assert.notEqual(r.tasks.workRoot(admin,other.id),r.tasks.workRoot(admin,child.id));
});
test('one message addressed to two bots is one work with two assignments; private rooms do not cross',t=>{
 const {r,admin,a,aa,b,ba,room}=fixture(t);r.submit(admin,crypto.randomUUID(),room.id,'二人で検証',[a.id,b.id]);const one=r.tasks.claim(admin)!,two=r.tasks.claim(admin)!;
 r.registerBusinessTask(r.agentSession(one.task.agent_id),one,'検証','第一');r.registerBusinessTask(r.agentSession(two.task.agent_id),two,'検証','第二');assert.equal(r.businessTasks(admin).length,1);assert.equal(r.tasks.workRoot(admin,one.task.id),r.tasks.workRoot(admin,two.task.id));
 const privateRoom=r.createRoom(admin,'個別',[a.id]),privateTask=r.tasks.create(admin,a.id,privateRoom.id,'二人で検証');assert.throws(()=>r.tasks.workRoot(ba,privateTask.id));
});
test('thread grouping keeps different purposes, folds terminals and prioritizes live assignments without changing input',async()=>{
 const {groupThreadWork}=await import(pathToFileURL(resolve('web/src/work-groups.js')).href);
 const tasks=[{id:'a',work_root_id:'a',thread:'room',member:'one',business:true,state:'waiting_child',status:'waiting',title:'調査',updated_at:1},{id:'b',work_root_id:'a',thread:'room',member:'two',business:true,state:'running',status:'running',title:'資料照合',updated_at:3},{id:'c',work_root_id:'c',thread:'room',member:'one',business:true,state:'queued',status:'running',title:'別の試作',updated_at:2},{id:'d',work_root_id:'d',thread:'room',member:'two',business:true,state:'completed',status:'done',title:'旧仕事',updated_at:4},{id:'e',work_root_id:'e',thread:'old',member:'two',business:true,state:'cancelled',status:'canceled',title:'中止',updated_at:8}];const original=JSON.stringify(tasks);const groups=groupThreadWork(tasks,[{id:'room',title:'案件'},{id:'old',title:'履歴'}]);assert.equal(groups.length,2);assert.equal(groups[0].id,'room');assert.equal(groups[0].active.length,2);assert.equal(groups[0].active[0].tasks.length,2);assert.equal(groups[0].history.length,1);assert.equal(groups[1].active.length,0);assert.equal(JSON.stringify(tasks),original);
});
test('explicit continuing initiative reuses its work registration across wake cycles',t=>{
 const {r,admin,a,aa,room}=fixture(t);r.initiatives.enable(admin,true);const first=r.tasks.create(admin,a.id,room.id,'継続調査'),lease=r.tasks.claim(admin)!;
 r.initiatives.save(aa,lease,{id:null,expected_revision:0,body:{purpose:'販売方法を比較する',reason:'比較に関心がある',completion:'根拠を確認する',next_action:'資料を読む',method:'比較',last_result:'未着手',participants:[a.id],workarea:null,artifacts:[],wait:{kind:'none',detail:'',task_id:null}},state:'active',review_at:0});r.registerBusinessTask(aa,lease,'継続調査','資料を比較する');r.tasks.finish(aa,lease,'初回の結果');const now=Date.now();r.autonomousWakes.dispatch(admin,now);r.autonomousWakes.dispatch(admin,now+60001);const next=r.tasks.claim(admin)!;assert.notEqual(next.task.id,first.id);r.registerBusinessTask(aa,next,'続きの検証','前の結果を使う');assert.equal(r.tasks.workRoot(admin,next.task.id),first.id);assert.equal(r.businessTasks(admin).length,1);
});
